### ISSUE TITLE
GitHub doesn't allow '~' in asset names

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-devtools#15]
We currently have mintty in the queue which has an epoch set, so the version is `1~3.3.0-1`. GitHub normalizes that to `1.3.3.0-1`, so it is never considered done.

* We need some way to fix that.
* We need to make sure this doesn't happen for other cases and ideally check that the filename hasn't changed after the upload.

**Comment by lazka** [comment]
Maybe we can use the label to encode the real filename. I need to test that with the API.

**Comment by eine** [comment]
> Maybe we can use the label to encode the real filename. I need to test that with the API.

Yes. E.g., in eine/tip, the label is not used when uploading the asset (https://github.com/eine/tip/blob/master/tip.py#L119). However, `label` is an optional argument. Then, the name and label are set to the same value (https://github.com/eine/tip/blob/master/tip.py#L123), but it is possible to rename the file and set a different label.

**Comment by jeremyd2019** [comment]
I hit that too.  I just renamed such files before adding them to the pacman db.
```bash
# work around github issue with ~ in file name (turns into .)
for a in *~*; do
    mv "$a" "`tr '~' '.' <<<"$a"`"
done
```

**Comment by Biswa96** [comment]
Is it possible to not use epoch?
