### ISSUE TITLE
Make the build dir path shorter

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-devtools#8]
It's currently `D:\\a\\msys2-devtools\\msys2-devtools\\_tmp\\MINGW-packages` which likely makes various builds fail because it results in too long paths.

**Comment by 1480c1** [comment]
I do know that rust packages sometimes might fail with 60 chars in the `%CD%` variable from cmd due to too long of a command line for ar.

I've limited the max chars to 32 in a project of mine to circumvent that for now

**Comment by lazka** [comment]
yeah, I think cargo-c is failing because of this, which is a rust package

**Comment by lazka** [comment]
cargo-c worked now.
